# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='phone_number',
            field=models.CharField(blank='True', max_length=20, null=True),
        ),
    ]
