"""
Django settings for parking project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'flyyu)po656qy#z9iel9ac(v&1b-u&4w7yv$#np!k_(k58vb^1'

# SECURITY WARNING: don't run with debug turned on in production!
# set to False in release build
DEBUG = True


# uncomment to force https connections
#SECURE_SSL_REDIRECT = True

# allow host komboparking.pythonanywhere.com in release
ALLOWED_HOSTS = []

# Application definition

# installed applications
INSTALLED_APPS = [
    'account.apps.AccountConfig',
    'main.apps.MainConfig',
    'kombo_parking.apps.KomboParkingConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# root urls
ROOT_URLCONF = 'parking.urls'

# template options & directories & loaders & backend
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# wsgi
WSGI_APPLICATION = 'parking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# database in use
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

# password validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# set url for media & static
#MEDIA_URL = '/media/'
STATIC_URL = '/static/'

#~ STATICFILES_DIRS = (
    #~ os.path.join(os.path.dirname(__file__), 'static').replace('\\','/'),
#~ )

STATICFILES_DIRS = (
    "/main/static/main/",
    os.path.join(
        os.path.dirname(__file__),
        'static',
    ),
)

# set media root
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# configure email
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'komboparking@gmail.com'
SERVER_EMAIL = 'komboparking@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'komboparking@gmail.com'
EMAIL_HOST_PASSWORD = '4H8FyXrArf'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
