# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('parkering', '0002_auto_20161123_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('own_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkering.Parkspace')),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='own_space',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
