# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkering', '0003_auto_20161123_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkspace',
            name='avail_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkspace',
            name='avail_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkspace',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='own_space',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parkering.Parkspace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
