# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('parkering', '0005_auto_20161123_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('own_space', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parkering.Parkspace')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='own_space',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
