# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('parkering', '0006_auto_20161123_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Extended',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('own_space', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parkering.Parkspace')),
            ],
        ),
        migrations.RemoveField(
            model_name='renter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='own_space',
        ),
        migrations.DeleteModel(
            name='Renter',
        ),
    ]
